// <auto-generated />
using System;
using LabManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabManagementSystem.Migrations
{
    [DbContext(typeof(LabContext))]
    [Migration("20260919093319_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabManagementSystem.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<int>("TableName")
                        .HasColumnType("int");

                    b.Property<int>("TableRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Audits_UserId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("LabManagementSystem.Models.BaseExternalLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseExternalLabs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ExternalLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseExternalLabId")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeReceive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeSend")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VistLabId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BaseExternalLabId" }, "IX_ExternalLabs_BaseExternalLabId");

                    b.HasIndex(new[] { "VistLabId" }, "IX_ExternalLabs_VistLabId");

                    b.ToTable("ExternalLabs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<int>("LabCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LabCategoryId" }, "IX_Labs_LabCategoryId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LabCategorys");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsNumeric")
                        .HasColumnType("bit");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<int>("LabParametersCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NormalRangeMax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("NormalRangeMin")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NormalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GenderId" }, "IX_LabParameters_GenderId");

                    b.HasIndex(new[] { "LabId" }, "IX_LabParameters_LabId");

                    b.HasIndex(new[] { "LabParametersCategoryId" }, "IX_LabParameters_LabParametersCategoryId");

                    b.ToTable("LabParameters");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabParameterCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LabId" }, "IX_LabParameterCategory_LabId");

                    b.ToTable("LabParameterCategory", (string)null);
                });

            modelBuilder.Entity("LabManagementSystem.Models.Need", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("Needs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LabManagementSystem.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderDetails_OrderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderDetails_ProductId");

                    b.HasIndex(new[] { "UnitId" }, "IX_OrderDetails_UnitId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeAtRecord")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GenderId" }, "IX_Patients_GenderId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VisitId" }, "IX_Payments_VisitId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialAmount")
                        .HasColumnType("int");

                    b.Property<int>("MinAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BaseUnitId" }, "IX_Products_BaseUnitId");

                    b.HasIndex(new[] { "ProductCategoryId" }, "IX_Products_ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ParentCategoryId" }, "IX_ProductCategorys_ParentCategoryId");

                    b.ToTable("ProductCategorys");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionToBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(1.0m);

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductUnits_ProductId");

                    b.HasIndex(new[] { "UnitId" }, "IX_ProductUnits_UnitId");

                    b.ToTable("ProductUnits");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ProductUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int?>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductUsages_ProductId");

                    b.HasIndex(new[] { "UnitId" }, "IX_ProductUsages_UnitId");

                    b.HasIndex(new[] { "VisitId" }, "IX_ProductUsages_VisitId");

                    b.ToTable("ProductUsages");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("LabManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DrName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "IX_Visits_PatientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("LabManagementSystem.Models.VisitLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<decimal>("LabPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<int>("VisitLabStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LabId" }, "IX_VisitLabs_LabId");

                    b.HasIndex(new[] { "VisitId" }, "IX_VisitLabs_VisitId");

                    b.HasIndex(new[] { "VisitLabStatusId" }, "IX_VisitLabs_VisitLabStatusId");

                    b.ToTable("VisitLabs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.VisitLabResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LabParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitLabId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LabParameterId" }, "IX_VisitLabResults_LabParameterId");

                    b.HasIndex(new[] { "VisitLabId" }, "IX_VisitLabResults_VisitLabId");

                    b.ToTable("VisitLabResults");
                });

            modelBuilder.Entity("LabManagementSystem.Models.VisitLabStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.ToTable("VisitLabStatus", (string)null);
                });

            modelBuilder.Entity("LabManagementSystem.Models.Audit", b =>
                {
                    b.HasOne("LabManagementSystem.Models.User", "User")
                        .WithMany("Audits")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ExternalLab", b =>
                {
                    b.HasOne("LabManagementSystem.Models.BaseExternalLab", "BaseExternalLab")
                        .WithMany("ExternalLabs")
                        .HasForeignKey("BaseExternalLabId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.VisitLab", "VistLab")
                        .WithMany("ExternalLabs")
                        .HasForeignKey("VistLabId")
                        .IsRequired();

                    b.Navigation("BaseExternalLab");

                    b.Navigation("VistLab");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Lab", b =>
                {
                    b.HasOne("LabManagementSystem.Models.LabCategory", "LabCategory")
                        .WithMany("Labs")
                        .HasForeignKey("LabCategoryId")
                        .IsRequired();

                    b.Navigation("LabCategory");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabParameter", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Gender", "Gender")
                        .WithMany("LabParameters")
                        .HasForeignKey("GenderId");

                    b.HasOne("LabManagementSystem.Models.Lab", "Lab")
                        .WithMany("LabParameters")
                        .HasForeignKey("LabId");

                    b.HasOne("LabManagementSystem.Models.LabParameterCategory", "LabParametersCategory")
                        .WithMany("LabParameters")
                        .HasForeignKey("LabParametersCategoryId")
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Lab");

                    b.Navigation("LabParametersCategory");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabParameterCategory", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Lab", "Lab")
                        .WithMany("LabParameterCategories")
                        .HasForeignKey("LabId")
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabManagementSystem.Models.OrderDetail", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.Unit", "Unit")
                        .WithMany("OrderDetails")
                        .HasForeignKey("UnitId")
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Patient", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Gender", "Gender")
                        .WithMany("Patients")
                        .HasForeignKey("GenderId")
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Payment", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Visit", "Visit")
                        .WithMany("Payments")
                        .HasForeignKey("VisitId")
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Product", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Unit", "BaseUnit")
                        .WithMany("Products")
                        .HasForeignKey("BaseUnitId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ProductCategory", b =>
                {
                    b.HasOne("LabManagementSystem.Models.ProductCategory", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ProductUnit", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Product", "Product")
                        .WithMany("ProductUnits")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.Unit", "Unit")
                        .WithMany("ProductUnits")
                        .HasForeignKey("UnitId")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ProductUsage", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Product", "Product")
                        .WithMany("ProductUsages")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.Unit", "Unit")
                        .WithMany("ProductUsages")
                        .HasForeignKey("UnitId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.Visit", "Visit")
                        .WithMany("ProductUsages")
                        .HasForeignKey("VisitId");

                    b.Navigation("Product");

                    b.Navigation("Unit");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Visit", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabManagementSystem.Models.VisitLab", b =>
                {
                    b.HasOne("LabManagementSystem.Models.Lab", "Lab")
                        .WithMany("VisitLabs")
                        .HasForeignKey("LabId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.Visit", "Visit")
                        .WithMany("VisitLabs")
                        .HasForeignKey("VisitId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.VisitLabStatus", "VisitLabStatus")
                        .WithMany("VisitLabs")
                        .HasForeignKey("VisitLabStatusId")
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Visit");

                    b.Navigation("VisitLabStatus");
                });

            modelBuilder.Entity("LabManagementSystem.Models.VisitLabResult", b =>
                {
                    b.HasOne("LabManagementSystem.Models.LabParameter", "LabParameter")
                        .WithMany("VisitLabResults")
                        .HasForeignKey("LabParameterId")
                        .IsRequired();

                    b.HasOne("LabManagementSystem.Models.VisitLab", "VisitLab")
                        .WithMany("VisitLabResults")
                        .HasForeignKey("VisitLabId")
                        .IsRequired();

                    b.Navigation("LabParameter");

                    b.Navigation("VisitLab");
                });

            modelBuilder.Entity("LabManagementSystem.Models.BaseExternalLab", b =>
                {
                    b.Navigation("ExternalLabs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Gender", b =>
                {
                    b.Navigation("LabParameters");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Lab", b =>
                {
                    b.Navigation("LabParameterCategories");

                    b.Navigation("LabParameters");

                    b.Navigation("VisitLabs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabCategory", b =>
                {
                    b.Navigation("Labs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabParameter", b =>
                {
                    b.Navigation("VisitLabResults");
                });

            modelBuilder.Entity("LabManagementSystem.Models.LabParameterCategory", b =>
                {
                    b.Navigation("LabParameters");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ProductUnits");

                    b.Navigation("ProductUsages");
                });

            modelBuilder.Entity("LabManagementSystem.Models.ProductCategory", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Unit", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ProductUnits");

                    b.Navigation("ProductUsages");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("LabManagementSystem.Models.User", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("LabManagementSystem.Models.Visit", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ProductUsages");

                    b.Navigation("VisitLabs");
                });

            modelBuilder.Entity("LabManagementSystem.Models.VisitLab", b =>
                {
                    b.Navigation("ExternalLabs");

                    b.Navigation("VisitLabResults");
                });

            modelBuilder.Entity("LabManagementSystem.Models.VisitLabStatus", b =>
                {
                    b.Navigation("VisitLabs");
                });
#pragma warning restore 612, 618
        }
    }
}
